CREATE TABLE USERS
(
    ID            BIGSERIAL PRIMARY KEY,
    USER_NAME     VARCHAR NOT NULL UNIQUE,
    EMAIL         VARCHAR NOT NULL,
    HASH_PASSWORD VARCHAR NOT NULL,
    ROLE          VARCHAR NOT NULL DEFAULT 'Default'
);

CREATE TABLE ITEMS
(
    ID             BIGSERIAL PRIMARY KEY,
    NAME           VARCHAR NOT NULL,
    PRICE          NUMERIC NOT NULL,
    IMAGE          VARCHAR NOT NULL,
    COUNT_OF_VIEWS INT8    NOT NULL DEFAULT 0,
    DESCRIPTION    VARCHAR NOT NULL,
    CATEGORY       VARCHAR NOT NULL DEFAULT 'Other',
    STATUS         VARCHAR NOT NULL,
    ADDRESS        VARCHAR NOT NULL,
    USER_ID        BIGINT  NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE RENTS
(
    ID              BIGSERIAL PRIMARY KEY,
    PERIOD_TYPE     VARCHAR NOT NULL,
    COUNT_OF_PERIOD BIGINT  NOT NULL,
    ITEM_ID         BIGINT  NOT NULL REFERENCES ITEMS (ID) ON DELETE CASCADE,
    USER_ID         BIGINT  NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE
);